### ISSUE TITLE
integration with active resource

### ISSUE THREAD

**Issue by tansaku** [mbleigh/twitter-auth#13]
Would be great if twitter-auth integrated with active resource.  There is an oauth activeresource plugin:

http://blog.behindlogic.com/2008/03/activeresource-oauth-plugin.html

Not sure how much it would take to integrate with twitter-auth, but would be really useful given twitter's throttling of queries.

Many thanks in advance
CHEERS> SAM

**Comment by mbleigh** [comment]
ActiveResource-based Twitter API access would be interesting, but how would that help with API throttling? That would actually cause more requests to the API since instead of mirroring user data locally a new API call would be made each time the resource was accessed.

**Comment by tansaku** [comment]
I was thinking that ActiveResource can be plugged into caching systems that can be set to expire with the appropriate frequency for twitter

**Comment by tansaku** [comment]
e.g. activesupport

**Comment by mbleigh** [comment]
While there's nothing stopping users of TwitterAuth from implementing something along these lines (caching) on their own, I will not be going down this road in the official repository.
