### ISSUE TITLE
calling /sessions/destroy then /login never gives you an opportunity to re-authenticate as a different user

### ISSUE THREAD

**Issue by kylebragger** [mbleigh/twitter-auth#17]
Is this something that must be handled by the user via revoking access to the app, then hitting /login again?

**Comment by mbleigh** [comment]
This is actually better solved by logging out of Twitter on the user side. If you want your app to be usable by multiple people more easily, change the authorization URL to /oauth/authorize instead of /oauth/authenticate. It will then provide a chance to log out if you're already registered.

**Comment by kylebragger** [comment]
Ah, thanks!
