### ISSUE TITLE
How to use twitter-auth with Rails 3.0

### ISSUE THREAD

**Issue by aslamnd** [mbleigh/twitter-auth#29]
Can anyone please give clear instruction to how to use twitter-auth with Rails 3.0?

**Comment by krzkrzkrz** [comment]
Am also wondering if this working on rails 3. Were you able to get this to work? Is this gem still supported?

**Comment by aslamnd** [comment]
I tried many times, but no luck. I even sent a message to the author. :(

**Comment by revathskumar** [comment]
Some fork of this repo is maintained for rails 3. check this [fork](https://github.com/jaikoo/twitter-auth) branch : rails_3
I found this from [stackoverflow](http://stackoverflow.com/questions/4652785/trying-to-get-the-twitter-auth-api-to-work-getting-no-such-file-to-load-loade)

But still found some issues. :(

**Comment by aslamnd** [comment]
I believe the best choice is to use [OmniAuth](https://github.com/intridea/omniauth).
