### ISSUE TITLE
Abnormal file size of debug.log in 'spec' folder

### ISSUE THREAD

**Issue by mysen** [mbleigh/twitter-auth#6]
Hi there, I'm a window git user. I have just installed your twitter-auth gem, I'm so glad that I found a really nice one.
Two things that frustrated me at first, let me tell you what:
first, the gem costed me more than a half hour to complete, I found out that the file size of 'C:\ruby\lib\ruby\gems\1.8\gems\twitter-auth-0.1.17\spec\debug.log' is over 208M. It must be a slip of mind, please clean up the file ASAP.
second,  'script/plugin install git://github.com/mbleigh/twitter-auth.git' can do nothing at present, is it the same reason related to the first one?

**Comment by mbleigh** [comment]
I have scrubbed the log out of the git history and the folder for me locally is now 1.2 megs instead of 208. Hope that helps!
