### ISSUE TITLE
Missing dependency in init.rb

### ISSUE THREAD

**Issue by chancancode** [mbleigh/twitter-auth#8]
init.rb is not listing 'json' as a dependency.

**Comment by mbleigh** [comment]
I fixed this at some point but I'm not sure exactly when.

**Comment by chancancode** [comment]
I might be missing something, but as of now there is a "require 'json'" line, but missing the corresponding "config.gem 'json'" line.

**Comment by mbleigh** [comment]
I didn't add config.gem 'json' since there are so many different JSON libraries that are available. If you're on JRuby for example, you can't use the 'json' gem and have to use json pure instead. I would recommend adding it to your app's env.rb; I may update the documentation soon to reflect this.
