### ISSUE TITLE
OauthUser.identify_or_create_from_access_token won't work for strings

### ISSUE THREAD

**Issue by chancancode** [mbleigh/twitter-auth#9]
Despite the error message from the first line of <code>OauthUser.identify_or_create_from_access_token</code> (<code>oauth_user.rb</code> line 14) said "Must authenticate with an OAuth::AccessToken or the <strong>string access token and secret.</strong>" - it actually won't work for Strings. The next line will cause a <code>NoMethodError / String#get</code>.

My use case for using string tokens and secrets:
My app has an "app user" and I need to parse the timeline of this app user. I saved the app user's token and secret in twitter_auth.yml and I need to be able to create an OauthUser based on these credentials.

**Comment by chancancode** [comment]
Patch submitted.

**Comment by mbleigh** [comment]
Accepted patch.
